version: '3.3'
services:
  api:
    container_name: courses_api
    image: courses_api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3333:3333'
    networks:
      - courses-network
networks:
  courses-network:
    driver: bridge
