version: '3.4'

services:
  api:
    container_name: courses_api_prod
    image: courses_api_prod
    build:
      context: .
      dockerfile: ./apps/api/.Docker/prod.Dockerfile
  web:
    container_name: courses_web_prod
    image: courses_web_prod
    build:
      context: .
      dockerfile: ./apps/courses-react/.Docker/prod.Dockerfile
